[[main]]
  identifier = "关于"
  name = "关于"
  url = "/about/"
  weight = 5

[[main]]
  identifier = "归档"
  name = "归档"
  url = "/archive/"
  weight = 4

[[main]]
  identifier = "Coder"
  name = "Coding"
  url = "/techposts/"
  weight = 1
    
[[main]]
  identifier = "杂感"
  name = "杂感"
  url = "/essays/"
  weight = 2
    
[[main]]
  identifier = "笔记"
  name = "笔记"
  url = "/notes/"
  weight = 3
